server:
  port: 8080


spring:
  application:
    name: cy_generator
  datasource:
    url: jdbc:postgresql://localhost:5432/cv_generator
    username: anish
    password: postgres
  ##    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: /home/anish/Documents/office/java/CROSS-BORDER/cv-generator/Files
#  flyway:
#    enabled: true
#    locations: classpath:db/migration/postgresql

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
    operations-sorter: method